:scrollbar:
:data-uri:
:noaudio:

== SOAP Services

* Protocol 
* Function driven
* WS-Security
* Calls cannot be cached
* Heavy payload
* Data Format: XML


ifdef::showscript[]

=== Transcript

REST is an architecture that’s more data-driven; whereas SOAP is a standardized protocol for transferring structured information that’s more function-driven. This, coupled with the fact that a lot of existing web service architecture was developed with SOAP/XML, makes it a common requirement to support SOAP web services in API Management.

SOAP (Simple Object Access Protocol) is its own protocol, and is a bit more complex by defining more standards than REST — things like security and how messages are sent.  These built-in standards do carry a bit more overhead, but can be a deciding factor for organizations that require more comprehensive features in the way of security, transactions, and ACID (Atomicity, Consistency, Isolation, Durability) compliance. 

SOAP has tighter security. WS-Security, in addition to SSL support, is a built-in standard that gives SOAP some more enterprise-level security features.





endif::showscript[]
