:scrollbar:
:data-uri:


== Manage Non-REST APIs

* Separation of concerns
* Red Hat JBoss Fuse as integration platform:
** Camel route exposing REST/HTTP endpoint
** Camel producer endpoint using non-REST endpoint
* Support transformation and encryption capabilities



ifdef::showscript[]

Transcript:

Frequently, there are requirements for Red Hat 3scale API Management to support enterprise integration capabilities such as multiple transport protocols or payload data types, data transformation, and payload encryption and enrichment. While some of these use cases may be trivial and can be handled using custom Lua modules, it is good idea to have a separation of concerns between the API management and integration layers. Red Hat recommends the JBoss Fuse product for enterprise integration scenarios.

With Red Hat JBoss Fuse, it is trivial to support any number of transport protocols, data types, and payload transformation and encryption capabilities. This product uses the popular Apache Camel library to provide routing and mediation capabilities.

The Camel route can expose a REST/HTTP endpoint to be used in Red Hat 3scale API Management as the back-end API, and in turn route the request to the actual provider API endpoint using the protocol expected, like SOAP or JMS.


endif::showscript[]
