:scrollbar:
:data-uri:


== Manage Non-REST APIs

* APIcast gateway customization for HTTP protocol
* Use code plug-ins for other protocols such as TCP
* Use custom Lua modules
* Example: SOAP:
** Match `SOAPAction` header
** Create mapping rule for `POST` operation
** Create method for each SOAP endpoint
** Create metrics for each SOAP operation



ifdef::showscript[]

Transcript:


Because the APICast gateway is built on top of NGINX, Lua, and OpenResty, it supports the HTTP protocol. Therefore, any non-REST APIs that uses an HTTP transport layer can be supported in APIcast with custom modules. For APIs using other protocols, a traffic controller needs to be created using code plug-ins and mappings, methods, and metrics matched to the API.

An example of using custom Lua modules would be to support a SOAP API provider. Here, because SOAP uses `POST` requests with a `SOAPAction` header, the Lua script has to provide special methods to NGINX for the `urlrewrite` response from SOAP endpoints.

Mapping rules in a 3scale service need to be defined in such a way that each SOAP endpoint has a method definition, because the URL is unique for each endpoint. Each operation for the SOAP endpoint can be defined in metrics so that 3scale can provide fine-grained metrics on the SOAP operations.


endif::showscript[]
