:scrollbar:
:data-uri:
:linkattrs:
:toc2:


== Environment Registration & Business Services Lab

In this lab you familiarize yourself with the course's lab assets and deploy RESTful business services to Red Hat OpenShift Container Platform.

.Goals
* Review lab environment and client VM setup
* Learn about the course's lab assets
* Deploy business service APIs in your OpenShift environment


:numbered:
== Environment Registration

This course uses the same lab environment that you have originally provisioned for the pre-requisite course `Red Hat 3scale API Management Implementation`. Hence, please continue to use the same OpenShift Container Platform and Virtual Machine for running the labs in this course.

NOTE: The OPENTlc lab environment gets deleted automatically after 14 days, hence please login to https://labs.opentlc.com and extend the lifetime of your environment by 1 more week. 

== Explore Lab Assets

To support the lab exercises, you need API RESTful business services that you can manage and secure. These are provided in the lab assets. In this exercise, you explore these business services.

. At the shell prompt of your VM, verify that you are the `jboss` user.
. Change to the `$HOME/lab/` directory.
. Clone the latest `3scale_developer_labs`:
+
[source,text]
-----
$ git clone https://github.com/gpe-mw-training/3scale_development_labs
-----

. Examine the subdirectory structure of the labs and note the available subprojects:
* *Products*: JEE application that exposes a JAX-RS REST API. This is the business API that you manage using Red Hat 3scale API Management.
*Stores* : JBoss EAP application that exposes a CXF SOAP API web service.
* *StoresFIS*:  JBoss Fuse camel application that exposes a REST API and routes to the Stores SOAP service.
* *templates*: OpenShift templates for defining the service build and deployment parameters of your project.
* *3scale-Swagger-Import*: Custom tool for importing API definitions using OpenAPI Specifications (OAS) into Red Hat 3scale API Management.
* *DevPortal*: Files related to customizing 3scale by Red Hat's Developer Portal.
* *Stock* : JBoss Data Virtualization application providing a REST API for accessing Stock details across PostgreSQL and MySQL databases.

[[bservice_deployment]]
== Deploy Products API Services in OpenShift Container Platform

In this section you deploy the Products API on a Red Hat JBoss Enterprise Application Platform (EAP) container running on OpenShift. The products data exists in a PostgreSQL database, which is deployed to the same OpenShift namespace.

IMPORTANT: When executing commands using the `oc` utility, you must be logged in to the master API of your OpenShift environment with your `OCP_USER_ID` credentials.


=== Create New Project for Products API Services

. Create a new project for your Products API business service applications:
+
[source,text]
-----
$ oc new-project $OCP_PROJECT_PREFIX-products-api \
     --display-name="Products API" \
     --description="Products API Business Services"
-----

. If you are not already there, change to this new project:
+
[source,text]
-----
$ oc project $OCP_PROJECT_PREFIX-products-api
-----

=== Deploy and Test `products` API Service

. Import the `products-api` template to your OpenShift environment:
+
[source,text]
-----
$ oc create -f /home/jboss/lab/3scale_development_labs/templates/products-api.json
-----
+
. Create a new application using the `products-api` template:
+
[source,text]
-----
$ oc new-app --template=products-api --param HOSTNAME_HTTP=products-$OCP_PROJECT_PREFIX.$OCP_WILDCARD_DOMAIN
-----
+
. Test the `products` API service deployed in your OpenShift environment:

.. Wait until your `products-api` and `productsdb` pods have fully started:
+
[source,text]
-----
$ oc get pods
-----
+
.Sample Output
[source,text]
-----
NAME                               READY     STATUS      RESTARTS   AGE
products-api-1-02s28               1/1       Running     0          4m
productsdb-1-39dkc                 1/1       Running     0          5m
-----
+
NOTE: The pods should take about 2-3 minutes to reach `Running` status. Please confirm your pods are Running before executing the next steps.
+
.. Get the route details:
+
[source,text]
-----
$ oc get routes
-----
+
.Sample Output
[source,text]
-----
NAME                       HOST/PORT                                                                                   PATH      SERVICES               PORT      TERMINATION   WILDCARD
products-api               products-sjayanti-redhat-com.apps.na1.openshift.opentlc.com                                                              products-api           <all>                   None
-----
+
.. Note the value for `HOST/PORT` for use in later labs. 

* This is the URL to connect to the Products API service. 
* It uses the format `http://products-$OCP_PROJECT_PREFIX.$OCP_WILDCARD_DOMAIN`.
.. Test that the `products` API service accepts requests and returns the correct response:
+
[source,text]
-----
$ curl -v -k http://products-$OCP_PROJECT_PREFIX.$OCP_WILDCARD_DOMAIN/rest/services/product/1
-----
+
.Sample Output
[source,text]
-----
..

{"productid":1,"productname":"Ninja Blender","productprice":320.0}
-----


The `products` REST API service is now running and exposed to external clients. In later lab exercises, you learn how to manage and secure these mock business services using Red Hat 3scale API Management.
