:scrollbar:
:data-uri:
:linkattrs:
:toc2:


== Environment Registration and Business Services Lab

In this lab you familiarize yourself with the course's lab assets and deploy RESTful business services to Red Hat OpenShift^(R)^ Container Platform.

.Goals
* Review lab environment and client VM setup
* Learn about the course's lab assets
* Deploy business service APIs in your OpenShift environment


:numbered:
== Environment Registration

This course uses the same lab environment that you provisioned in the prerequisite course that covered implementation of Red Hat 3scale API Management. To run the labs in this course, continue to use the same OpenShift Container Platform and virtual machine as you used in the previous course.

IMPORTANT: The OPENTLC lab environment is automatically deleted after 14 days. Therefore you must log in to the link:https://labs.opentlc.com[OPENTLC Lab portal^] and extend the lifetime of your environment by one more week. 

== Explore Lab Assets

To support the lab exercises, you need API RESTful business services that you can manage and secure. These are provided in the lab assets. In this exercise, you explore these business services.

. At the shell prompt of your VM, verify that you are the `jboss` user.
. Change to the `$HOME/lab/` directory.
. Clone the latest `3scale_developer_labs`:
+
[source,text]
-----
$ git clone https://github.com/gpe-mw-training/3scale_development_labs
-----

. Examine the subdirectory structure of the labs and note the available subprojects:
* *Products*: JEE application that exposes a JAX-RS REST API. This is the business API that you manage using Red Hat 3scale API Management.
* *Stores*: JBoss^(R)^ EAP application that exposes a CXF SOAP API web service.
* *StoresFIS*:  JBoss Fuse camel application that exposes a REST API and routes to the Stores SOAP service.
* *templates*: OpenShift templates for defining the service build and deployment parameters of your project.
* *3scale-Swagger-Import*: Custom tool for importing API definitions using OpenAPI Specifications (OAS) into Red Hat 3scale API Management.
* *DevPortal*: Files related to customizing 3scale by Red Hat's Developer Portal.
* *Stock* : JBoss Data Virtualization application providing a REST API for accessing Stock details across PostgreSQL and MySQL databases.
* *Coolstore* : Homework assignment assets based on the JBoss Demo CoolStore microservices application.

== Shell Environment Variables

Recall from the first lab of the _3scale Implementation_ pre-requisite course that you permanently set the following environment variables in shell of your virtual machine:

. *GUID*
. *OCP_WILDCARD_DOMAIN*
. *OCP_USER_ID*
. *OCP_PROJECT_PREFIX*

Ensure that all of these environment variables are still set.

=== (Re)-Set Environment Variables

For those that need to re-set the above listed environment variables in their shell, this section provides the same instructions for doing so found in the pre-req course.

The lab instructions assume the use of the `jboss` operating system user of the provide client side virtual machine.
If not using the virtual machine, you will still need these same environment variables set in your host operating system.

. As the `jboss` user, execute each of the following commands, one at a time:
+
[source,text]
-----
$ echo "export GUID=<your OCP lab environment GUID as provided in the confirmation email>" >> ~/.bashrc
$ echo 'export OCP_WILDCARD_DOMAIN=apps.$GUID.openshift.opentlc.com' >> ~/.bashrc
-----

. Set an environment variable with your OpenShift user Id:
+
-----
$ echo 'export OCP_USER_ID=<your OCP USER ID>' >> ~/.bashrc
-----
+
NOTE:  If you are an elabs student, then the value will be your opentlc userId.
Otherwise, if you are an ILT student, then the value will be that of the user assigned to you by your instructor.

. Set an environment variable with your initials:
+
[source,text]
-----
$ echo "export OCP_PROJECT_PREFIX=<your initials>" >> ~/.bashrc
-----
* OpenShift project names need to be unique within an OpenShift cluster, so this ensures that your project names begin with a unique prefix. This environment variable is used throughout the labs.

. Enable the new environment variables in your existing shell:
+
[source,text]
-----
$ source ~/.bashrc
-----


[[bservice_deployment]]
== Deploy Products API Services in OpenShift Container Platform

In this section you deploy the Products API on a Red Hat JBoss Enterprise Application Platform (EAP) container running on OpenShift. The products data exists in a PostgreSQL database, which is deployed to the same OpenShift namespace.

=== Optional: Understand the Products API

The lab assets that you previously cloned include everything needed to build and run the _Products API_.

Specific to the Products API, study the following from your lab assets:

. *~/lab/3scale_development_labs/templates/products-api.json*
. *~/lab/3scale_development_labs/Products/src/main/java*

To test your understanding of the _Products API_ assets, answer the following questions:

. What source code is compiled in the _BuildConfig_ object responsible for creating the Products container image ?
. How is the PostgreSQL based Products database seeded with data ?
. The REST API of the Products service will generate a _swagger.yaml_ configuration file that defines the resources and HTTP methods exposed by the API.
+
This _swagger.yaml_ is exposed by the Products service at runtime and can be viewed in a tool such as:  http://editor.swagger.io .
+
What is used to generate the _swagger.yaml_ configuration ?


=== Create New Project for Products API Services

. Using the `oc` utility found in the course virtual machine, log into the master API of your OpenShift environment.
+
NOTE: The login session to your OpenShift environment is valid for 24 hours.  Every 24 hours, you'll have to re-authenticate using the `oc` utility and subsequently re-generate a new session.

. Create a new project for your Products API business service applications:
+
[source,text]
-----
$ oc new-project $OCP_PROJECT_PREFIX-products-api \
     --display-name="Products API" \
     --description="Products API Business Services"
-----

. If you are not already there, change to this new project:
+
[source,text]
-----
$ oc project $OCP_PROJECT_PREFIX-products-api
-----

=== Deploy and Test `products` API Service

. Import the `products-api` template to your OpenShift environment:
+
[source,text]
-----
$ oc create -f ~/lab/3scale_development_labs/templates/products-api.json
-----
+
. Create a new application using the `products-api` template:
+
[source,text]
-----
$ oc new-app --template=products-api --param HOSTNAME_HTTP=products-$OCP_PROJECT_PREFIX.$OCP_WILDCARD_DOMAIN
-----
+
. Test the `products` API service deployed in your OpenShift environment:

.. Wait until your `products-api` and `productsdb` pods have fully started:
+
[source,text]
-----
$ oc get pods
-----
+
.Sample Output
[source,text]
-----
NAME                               READY     STATUS      RESTARTS   AGE
products-api-1-02s28               1/1       Running     0          4m
productsdb-1-39dkc                 1/1       Running     0          5m
-----
+
NOTE: It takes about 2-3 minutes for the application to be deployed. Before continuing to the next steps, confirm that your pods show a `Running` status, that the related build is complete, and that there are no deployment tasks running.
+
.. Get the route details:
+
[source,text]
-----
$ oc get routes
-----
+
.Sample Output
[source,text]
-----
NAME                       HOST/PORT                                                                                   PATH      SERVICES               PORT      TERMINATION   WILDCARD
products-api               products-sjayanti-redhat-com.apps.na1.openshift.opentlc.com                                                              products-api           <all>                   None
-----
+
.. Note the value for `HOST/PORT` for use in later labs. 

* This is the URL to connect to the Products API service. 
* It uses the format `http://products-$OCP_PROJECT_PREFIX.$OCP_WILDCARD_DOMAIN`.
.. Test that the `products` API service accepts requests and returns the correct response:
+
[source,text]
-----
$ curl -v -k http://products-$OCP_PROJECT_PREFIX.$OCP_WILDCARD_DOMAIN/rest/services/product/1
-----
+
.Sample Output
[source,text]
-----
..

{"productid":1,"productname":"Ninja Blender","productprice":320.0}
-----


The `products` REST API service is now running and exposed to external clients. In later lab exercises, you learn how to manage and secure these mock business services using Red Hat 3scale API Management.

== Product API swagger.yaml

Your Products service provides a _swagger.yaml_ configuration file that defines the resources that it exposes.

To gain access to this _swagger.yaml_ config file, point your browser to the output of the following command:

-----
$ echo http://"$(oc get route/products-api -o template --template {{.spec.host}})"/rest/swagger.yaml
-----

You'll be able to download this _swagger.yaml_ configuration file to your local filesystem and skim through it.

You'll make use of this _swagger.yaml_ configuration file in the next lab.
