:scrollbar:
:data-uri:
:linkattrs:
:toc2:


== Business Services Lab

In this lab, you orient yourself with the course's lab assets and deploy RESTful business services to OpenShift Container Platform.

.Goals
* Learn about course lab assets
* Deploy Business service APIs in your OCP environment


:numbered:
== Explore Lab Assets

To support the lab exercises for this course, you need an API RESTful business services provider that you can manage and secure. These are provided in the lab assets. In this exercise, you explore these business services.

. At the shell prompt of your VM, make sure you are using the `jboss` user.
. Change to the `$HOME/lab/` directory.
. Clone the latest `3scale_developer_labs`:
+
[source,text]
-----
$ git clone https://github.com/gpe-mw-training/3scale_development_labs
-----

. Examine the subdirectory structure of the labs and note the sub-projects available:
* Products: A JEE application that exposes a JAX-RS REST API. This will be our business API which we manage using 3scale.
* Camel-webservice-FIS: A Fuse camel application that exposes a CXF SOAP API Web service. This will be used in the later modules to manage integration of SOAP webservices with 3scale.
* templates: Provides the OpenShift templates for defining the service build and deployment parameters of your project.
* 3scale-swagger-Import : A custom tool for importing API definitions using OpenAPI Specifications (OAS) into 3scale.
* DevPortal : 3scale development portal customisation related files.

[[bservice_deployment]]
== Deploy Products API Services in OpenShift Container Platform

In this section, we deploy the Products API, onto a JBoss EAP container running on OpenShift. The products data exists in a PostgreSQL database, and this will also be deployed to the same Openshift namespace.

IMPORTANT: When executing commands using the `oc` utility, you must be logged in to the master API of your OpenShift Container Platform environment with your OCP_USER_ID credentials.


=== Create New Project for Products API Services

. Create a new project for your Products API business service applications:
+
[source,text]
-----
$ oc new-project $OCP_PROJECT_PREFIX-products-api \
     --display-name="Products API" \
     --description="Products API Business Services"
-----

. If not already there, switch to this new project:
+
[source,text]
-----
$ oc project $OCP_PROJECT_PREFIX-products-api
-----

=== Deploy and Test Products API Service

. Import the products-api template to your Openshift environment
+
[source,text]
-----
$ oc create -f /home/jboss/lab/3scale_development_labs/templates/products-api.json
-----
+
. Create the new application using the above products-api template:
+
[source,text]
-----
$ oc new-app --template=products-api --param HOSTNAME_HTTP=products-$OCP_PROJECT_PREFIX.$OCP_WILDCARD_DOMAIN
-----
+
. Test the Products API service deployed in your OpenShift Container Platform environment:

.. Wait until your products-api and productsdb pods have fully started, and then get the route details:
+
[source,text]
-----
$ oc get pods
NAME                               READY     STATUS      RESTARTS   AGE
products-api-1-02s28               1/1       Running     0          4m
productsdb-1-39dkc                 1/1       Running     0          5m
$ oc get routes
NAME                       HOST/PORT                                                                                   PATH      SERVICES               PORT      TERMINATION   WILDCARD
products-api               products-sjayanti-redhat-com.apps.na1.openshift.opentlc.com                                                              products-api           <all>                   None
-----
+
.. Note the HOST/PORT above, this is the URL to connect to the Products API service. This will be `http://products-$OCP_PROJECT_PREFIX.$OCP_WILDCARD_DOMAIN`.
.. Now test that the Products API service is accepting requests and returning the right response:
+
[source,text]
-----
$ curl -v -k http://products-$OCP_PROJECT_PREFIX.$OCP_WILDCARD_DOMAIN/rest/services/product/1
-----
+
.Sample Output
[source,text]
-----
..

{"productid":1,"productname":"Ninja Blender","productprice":320.0}
-----


You now have the products REST API service running and exposed to external clients. In later lab exercises, you learn how to manage and secure these mock business services using Red Hat 3scale API Management.

endif::showscript[]
