:scrollbar:
:data-uri:
:noaudio:

== Use Cases

* API requirements
** Purpose
** Audience
** Functionality
** Access control and security
** Visibility
** API UX
* Defining APIs
* Integrating APIs with Red Hat 3scale API Management
* Managing API access (application plans, limits & pricing rules)
* Engaging developers
* Exposing API


ifdef::showscript[]

Transcript:

*Requirements:* To enable the development of API use cases, consider the following requirements:

* *Purpose:* Consider the typical reason to open up your API, or the implications of allowing customers or third parties to access your API. Is a single standard API compatible with multiple customers or do you need to provide bespoke integration?

* *Audience:* You will probably want to expose your API to individual developers as well as to potential partners, so it is important to begin with a clear vision of how you are going to differentiate between these two groups.

* *Functionality:* Once you have thought about your use cases and audience, think about how to enable them through your API. If your aim is to develop a platform, you may want to think about exposing multiple APIs. This gives you more fine-grained control over the services that you expose as well as the ability to track access to each API separately.

* *Access control and security:* Think about which resources you want to expose as well as the operations you will allow on them. Also think about usage limits, if any, that you want to impose on the methods available through your API. These will probably be based on customer segments, with private partners receiving a higher allowance than public developers. It is also important to choose the correct authentication method.

* *Visibility:* An important next step is to think about the signup flow you want potential partners or customers to follow to get access to your API. Consider providing a public Developer Portal to allow people to learn more about your API, and consider provisioning some sort of trial access with restricted functionality so they can do a proof of concept integration against your API.

* *API UX:* Once you have decided on all of the above, it is important to think about what the experience is going to be like for partners discovering and integrating with your API.

*Defining the APIs in 3scale:* Now create all of the endpoints that you want to expose and track as methods under an application plan. Methods are the means by which 3scale tracks API usage. You can set up a method for each of the HTTP methods available on the API endpoints for your API.

*Integrating the API:* Now that you have created all of the endpoints you want to expose and track and defined how your customers access your API, you need to set up the API gateway to easily integrate with Red Hat 3scale API Management. You need to choose whether to use APICast gateway or code plug-ins.

*Managing API access:* With the gateway set up, you can start creating application plans to allow different types of access to your API. Look at any limits you want to enforce on the different application plans, as well as any additional pricing rules for when developers go above their plan limits.

*Engaging developers:* Now that you have set up limits, the next step is to set up your Developer Portal so customers can find out more about the API, get their API credentials, and monitor their usage.

*Exposing the API:* Now you are ready to expose the API using Red Hat 3scale API Management. Promote the API to production, and expose the Developer Portal to have public access so that customers and partners can find and sign up for the API services.

endif::showscript[]
