:scrollbar:
:data-uri:


== Other Plans

* Account plans
** Configuration at account level
** Not limited to specific API service
** Apply to all APIs accessed by account

* Service plans
** Configuration at service level
** Not limited to specific application
** Apply to all applications accessing service

* End-user plans
** Configuration at end-user level
** Quotas can be applied to single user
** Prevent rate limits from being consumed wholly by single user


ifdef::showscript[]

Transcript:

Account plans establish pricing and features on the account level and thus are not limited to a specific API service. Account plans can be customized for each account.

Service plans establish pricing and features on the service level and thus are not limited to a specific application.

End-user plans establish usage limits and pricing rules for end users of an API. They allow you to balance the allowed number of hits specified in the application plans, preventing a single user from consuming the application plan's entire quota.


endif::showscript[]
