:scrollbar:
:data-uri:
:noaudio:

== API Management Steps

.Managing a New API (Service)

. API admin:
.. Create API deployment option (APIcast or plug-in)
.. Select authentication option (API key, app ID and app key, or OAuth 2.0)
.. Select user sign-up flows
.. Specify integration: back end (private base URL), staging, and production URLs
.. Create mapping rules and methods
.. Create application plans
. Accounts:
.. Create developer accounts
.. Create users and administrators
.. Create applications (with associated application plans)
. Create Developer Portal
. Create ActiveDocs API documentation
. Test the service on staging URL
. Promote to production



ifdef::showscript[]

Transcript:

This slide shows the steps needed to create a new API service to be managed using Red Hat 3scale API Management. Initially, there are two sets of steps. The first set of steps pertains to the API, and the second set involves accounts.

The first set of steps can be executed through either the Red Hat 3scale API Management console or the Admin API. This involves setting up the service--for example, providing the API gateway (using APIcast or a plug-in), the security options (either API key, app ID plus app key, or OAuth), user sign-up flows, and finally, the URLs for the service back end, staging, and production APIcast or plug-in URLs. In this section, you also need to define the methods and metrics, the mappings, and various application plans for the service.

The second set of steps involves setting up developer accounts (including users and administrators), applications and their associated application plans, and any additional configurations like group subscriptions, service subscriptions, and user invitations.

At a minimum, once these two sets of steps are completed, you are ready to test the API using the staging URL.

Steps 3 to 6 ensure that the API service is ready for production. The API providers create the Developer Portal, the API documentation, create sign-up flows and user self-service flows, and finally, test the service and promote the service to production.





endif::showscript[]
