:scrollbar:
:data-uri:
:noaudio:

== Rate Limits


* Threshold on usage of API by consumers
* Based on method, endpoint, or metric
* Associated with a plan
* Configure different limits for different developer segments
* Can send alerts based on limits
* API authorization fails if usage exceeds limit



ifdef::showscript[]

Transcript:

Rate limits allow you to throttle access to your API resources. You can configure different limits for separate developer segments through the use of application plans.

Once you have rate limits in place, these limits control the responses a developer receives when making authorization request calls to 3scale’s back end.

If you have alerts configured, the new limits are used to decide when notifications are sent.
When you make authorization calls to the 3scale back end, the limits are taken into account. If usage is above the limit, the response is an authorization failure. However, this is a soft rejection; your app ultimately decides how to handle the rejection.

Once your rate limits are operating, you can see the users who are reaching the limits on your dashboard, making it easy to check for potential candidates for a plan upgrade.

endif::showscript[]
