
:scrollbar:
:data-uri:


== Users and Rights on Admin Portal

* Two user types (roles):
** `admin`- full access to all areas, and member management
** `member` - limited access to certain areas or services

* Assign users rights on Admin Portal
** *By area* - access to section in Admin Portal and corresponding REST API
*** Developer Portal (Account Management API)
*** Analytics
*** Billing
** *By services*


ifdef::showscript[]

Transcript:

To share the workload of administering your APIs, you may wish to invite team members from your organization to access the Admin Portal.

The term _users_ refers to members of the administration team. The Admin Portal has two types of users, defined by role:

* `admin` users have full access to all areas and services, and can invite other members.
* `member` users have limited access to areas of the product--for example, analytics, the Developer Portal, and, if you’re an enterprise customer, also to services.

Members of your team can be assigned rights in two ways:

* *By area*: Such as analytics, billing, or developer administration.
* *By service*: Choose which services to give access to members.

Giving members access to certain areas of the Admin Portal gives them access only to the equivalent API.

endif::showscript[]
