:scrollbar:
:data-uri:
:noaudio:

== 3scale APIcast Gateway Deployment Options

Deployment Options:
* APIcast hosted (SaaS)
* APIcast built-in (AMP only)
* APIcast self-managed (SaaS or AMP)
** Native deployment
** docker
** OpenShift 


ifdef::showscript[]

=== Transcript

You can use APIcast hosted or self-managed, in both cases, it needs connection to the rest of the 3scale API management platform:

* APIcast hosted: 3scale hosts APIcast in the cloud. In this case, APIcast is already deployed for you and it’s limited to 50,000 calls per day.
* APIcast built-in: Two APIcast (staging and production) come by default with the 3scale API Management Platform (AMP) installation. They come pre-configured and ready to use out-of-the-box.
* APIcast self-managed: You can deploy APIcast wherever you want. The self-managed mode is the intended mode of operation for production environments. Here are a few recommended options to deploy APIcast:

**  Native deployment: Install OpenResty and other dependencies on your own server and run APIcast using the code and configuration provided by 3scale.
** Docker: Download a ready to use dockerized image which includes all of the dependencies to run APIcast in a docker container.
** OpenShift: Run APIcast on OpenShift Container Platform. You can connect self-managed APIcasts both to a 3scale AMP installation or to a 3scale online account.

endif::showscript[]
