:scrollbar:
:data-uri:
:noaudio:

== Code Plugins

* Community Extensions
* Allow API Traffic Management 
* Wrapper for Service Management API:
** API access control and security
** Traffic reporting
** API monetization
* Languages:
** Python
** Ruby gem
** Perl
** PHP
** Java
** .NET
** Node.js

ifdef::showscript[]

=== Transcript

3scale plugins allow you to connect to the 3scale architecture in a variety of core programming languages. Plugins can be deployed anywhere to act as control agents for your API traffic. 3scale API plugins are available for a variety of implementation languages including Java, Ruby, PHP, .NET, and others as shown above. The plugins provide a wrapper for the 3scale Service Management API. This wrapper connects back into the 3scale system to set and manage policies, keys, rate limits, and other controls that you can put in place through the interface. 

The code plugin libraries are available on the 3scale GitHub repository, and are released as Open source community extensions. 

endif::showscript[]
