:scrollbar:
:data-uri:
:noaudio:

== Lua

.Overview

* Scripting language
* Supports procedural, object-oriented, functional, data-driven programming
* Written in clean C
* Standalone or embedded
* No main; works embedded in host client
* Host invokes Lua functions
* Extendable using C functions

ifdef::showscript[]

Transcript:

Lua is a powerful, efficient, lightweight, embeddable scripting language. It supports procedural programming, object-oriented programming, functional programming, data-driven programming, and data description.

Lua combines simple procedural syntax with powerful data description constructs based on associative arrays and extensible semantics. Lua is dynamically typed, runs by interpreting bytecode with a register-based virtual machine, and has automatic memory management with incremental garbage collection, making it ideal for configuration, scripting, and rapid prototyping.

Lua is implemented as a library, written in clean C, the common subset of Standard C and C++. The Lua distribution includes a host program called lua, which uses the Lua library to offer a complete, standalone Lua interpreter for interactive or batch use. Lua is intended to be used both as a powerful, lightweight, embeddable scripting language, and a powerful, lightweight, and efficient standalone language.

As an extension language, Lua has no notion of a main program; it works embedded in a host client called the embedding program or simply the host. Frequently, this host is the standalone lua program. The host program can invoke functions to execute a piece of Lua code, can write and read Lua variables, and can register C functions to be called by Lua code. Through the use of C functions, Lua can be augmented to cope with a wide range of different domains, thus creating customized programming languages sharing a syntactical framework.

endif::showscript[]
