:scrollbar:
:data-uri:
:noaudio:

== OpenResty Web Platform

* Full-fledged web platform
* Integrates standard NGINX core
** LuaJIT
** Libraries
** Third-party NGINX modules
** `lua-nginx-module`
* Hook to NGINX request phases

ifdef::showscript[]

Transcript:

OpenResty is a full-fledged web platform that integrates the standard NGINX core, LuaJIT, many carefully written Lua libraries, lots of high-quality third-party NGINX modules, and most of their external dependencies. It is designed to help developers easily build scalable web applications, web services, and dynamic web gateways. OpenResty is not an NGINX fork. It is just a software bundle.

LuaJIT is a just-in-time compiler for the Lua programming language. The Lua interpreter or LuaJIT instance is shared across all of the requests in a single NGINX worker process, but request contexts are segregated using lightweight Lua co-routines.

`lua-nginx-module` is an NGINX module that makes it possible to handle HTTP requests directly in NGINX using Lua. Unlike Apache's `mod_lua` and Lighttpd's `mod_magnet`, Lua code executed using `lua-nginx-module` can be 100% nonblocking on network traffic as long as the NGINX API for Lua provided by this module is used to handle requests to upstream services such as MySQL, PostgreSQL, Memcached, Redis, or upstream HTTP web services.


endif::showscript[]
