:scrollbar:
:data-uri:


== Module Topics

* 3scale API Traffic Controllers
* 3scale APIcast Gateway
* NGINX Web Server
* OpenResty Web Platform
* APIcast Libraries
* APIcast Modules
* APIcast Configuration
* Lua
* Code Plug-ins


ifdef::showscript[]

Transcript:


This module introduces different API traffic controllers for 3scale. It begins with the 3scale API traffic management controllers, chiefly the APIcast gateway. The module continues with the NGNIX web server, including an overview, the basic architecture, the functional modules, and its integration with the OpenResty web platform. The APIcast libraries are discussed, with a mention of the extended NGNIX modules and the modules used primarily for internal purposes. Next the APIcast modules are covered, featuring the nine module phases and a look at the default module and custom modules, followed by APIcast configuration. The module concludes with an overview of Lua and its basic concepts and a discussion of code plug-ins.


endif::showscript[]
