:scrollbar:
:data-uri:


== 3scale ActiveDocs

* Instantiation of Swagger
* Interactive documentation served and rendered by Developer Portal
* Extensions to Swagger:
** Autofill API keys
** Swagger proxy to call non-CORS-enabled APIs
* OAuth-enabled API
** Client credentials flow
** Resource owner flow


ifdef::showscript[]

Transcript:

ActiveDocs is not a Swagger replacement--it is an instantiation of it. With ActiveDocs, you do not have to run your own Swagger server or deal with the UI components of the interactive documentation. The interactive documentation is served and rendered from your 3scale Developer Portal.

The only thing you need to do is build a Swagger-compliant specification of your API and add it to your Admin Portal, and the interactive documentation will be all set. Your developers can launch requests against your API through your Developer Portal.

ActiveDocs extends the Swagger specification in several ways to accommodate certain features needed for interactive API documentation in the 3scale Developer Portal:

* Autofill of API keys
* For business APIs that are not CORS enabled, a Swagger proxy that does allow for Cross-Origin Resource Sharing
+
NOTE: This is likely not very valuable any longer.  
The 3scale APIcast gateway itself can now be configured to support CORS.  
In addition, if using OAuth2 and RH-SSO, CORS enablement of your business APIs can be facilitated with these products.


With ActiveDocs, users can easily test and call your OAuth-enabled API from one place.



endif::showscript[]
