:scrollbar:
:data-uri:


== 3scale Developer Portal

* Hosted by Red Hat 3scale API Management
* Provides 3scale content management system (CMS) to quickly create custom portals
* Default Developer Portal available out of the box
* Built-in pages with HTML, CSS, JavaScript elements
* Liquid tags for processing and displaying data on portal
* Authentication options:
** Username and password
** GitHub
** Auth0
** Red Hat Single Sign-On

ifdef::showscript[]

Transcript:


The Developer Portal is the site where developers subscribe to APIs. From the Developer Portal, developers can manage their subscription, access their API keys, create applications, access the interactive API documentation (ActiveDocs), and see their API consumption. The out-of-the-box 3scale CMS features allow a developer to quickly create a Developer Portal with all that is required for on-boarding new customers. By default, it generates a default Developer Portal with functionality for sign-up, dashboard, account pages, and ActiveDocs. These can be customized as desired to meet the requirements of the API provider. 



endif::showscript[]
