:scrollbar:
:data-uri:


== 3scale Developer Portal

.CMS Overview


* Main section:
** Content: site structure, hierarchy, pages, assets
** Redirects: set up page redirects
** Changes: for draft and publish
* Content subsections:
** Content
** Layouts and partials
** Portlets
*** External RSS feed
*** Table of contents
*** Latest forum posts



ifdef::showscript[]

Transcript:


The CMS consists of the following elements:

* A horizontal menu in the Admin Portal with access to content, redirects, and changes
* The main area containing details of the sections 
* CMS mode, which is accessible through the preview option

The *Content* section shows the site structure and hierarchy and provides editing functionality so you can manage the site structure, the pages, and other assets stored in it. The portal’s hierarchy is displayed in the form of a directory tree.

*Redirects* help you set up redirects from one portal URL to another. This is useful, for example, when you deprecate an old page and don’t want to change all of the links.

The *layouts* and *partials* sections manage the templates and the reusable parts of the page. The functionality is similar to that of the content section. The layouts section consists of definitions of the templates used by pages. The layout is the main structure of the page, and the contents of this template is rendered on every page that uses it. Partials are the reusable parts of code that repeat in many places on different pages; for example, the footer is the same on every layout, and the sidebar is the same on a few pages with different layouts.

3scale's CMS also provides three different *portlets*:

* The external RSS feed fetches the RSS feed from a given source.
* The table of contents generates the links list for the pages in a given section.
* The latest forum posts generates a list of the _n_ latest forum posts.

endif::showscript[]
