:scrollbar:
:data-uri:


== Code Plug-ins

* Community extensions
* Allow API traffic management
* Wrapper for service management API:
** API access control and security
** Traffic reporting
** API monetization
* Languages:
+
[.noredheader,cols="50,50",width="70%"]
|======
a|
** Python
** Ruby gem
** Perl
** PHP
a|** Java
** .NET
** Node.js
|======

ifdef::showscript[]

Transcript:

Red Hat 3scale API Management plug-ins allow you to connect to the 3scale architecture using a variety of core programming languages. Plug-ins can be deployed anywhere to act as control agents for your API traffic. API plug-ins are available for a variety of implementation languages including Java, Ruby, PHP, .NET, and others as shown. The plug-ins provide a wrapper for the 3scale Service Management API. This wrapper connects back into the Red Hat 3scale API Management system to set and manage policies, keys, rate limits, and other controls that you can put in place through the interface.

The code plug-in libraries are available on the 3scale GitHub repository, and are released as open source community extensions.

endif::showscript[]
