:scrollbar:
:data-uri:


== 3scale Command Line Interface

* Command line utility for API management
* Functionality:
** Import and define API (Open API/Swagger, or RAML)
** Create interactive documentation (ActiveDocs)
* Manage (create, list, show, update, delete):
** Services
** Application plans
** Mapping rules
** Methods and metrics
** Applications
* List and show accounts
* Proxy and proxy configurations

NOTE: 3scale's command line interface (CLI) is an open source community project, not part of Red Hat 3scale API Management.

ifdef::showscript[]

Transcript:

3scale's CLI is a command line utility that can be used with Red Hat 3scale API Management SaaS and On-Premise. It is an open source project written in NodeJS, available from Node Package Manager. The source is available on GitHub.

Its main capabilities include:

* Importing and defining APIs (Open API/Swagger, or RAML)
* Creating interactive documentation (ActiveDocs)

Additionally, you can also:

* Create, list, show, update, and delete services, application plans, mapping rules, methods, metrics, and applications
* Suspend and resume applications
* List and show accounts
* Show and update proxies
* List, show, and promote proxy configurations



endif::showscript[]
