:scrollbar:
:data-uri:


== 3scale ActiveDocs

* Instantiation of Swagger
* Interactive documentation served and rendered by Developer Portal
* Extensions to Swagger:
** Autofill API keys
** Swagger proxy to call non-CORS-enabled APIs
* OAuth-enabled API
** Client credentials flow
** Resource owner flow


ifdef::showscript[]

Transcript:

ActiveDocs is not a Swagger replacement--it is an instantiation of it. With ActiveDocs, you do not have to run your own Swagger server or deal with the UI components of the interactive documentation. The interactive documentation is served and rendered from your 3scale Developer Portal.

The only thing you need to do is build a Swagger-compliant specification of your API and add it to your Admin Portal, and the interactive documentation will be all set. Your developers can launch requests against your API through your Developer Portal.

Red Hat 3scale API Management extended the Swagger specification in several ways to accommodate certain features that were needed for interactive API documentation:

* Autofill of API keys
* Swagger proxy to allow calls to non-CORS-enabled APIs

With ActiveDocs, users can easily test and call your OAuth-enabled API from one place.



endif::showscript[]
