:scrollbar:
:data-uri:
:noaudio:

== Liquid Tags

* Context - variables available to use on current page.
* Variables available for every page in CMS:
** provider
** urls
** current_user
** current_account
** today
* Additional variables for built-in pages
** Special tag: `{% debug:help %}`
** Adds comment on all available variables to the current page
* Hierarchy - access elements in the context as a hierarchical structure
** Current Username: `{{ current_user.username }}`
** Application name: `{{ current_account.applications.first.name }}`

ifdef::showscript[]

=== Transcript

The context describes which variables (drops) are available to use on the current page. The basic set includes the following variables:

* provider
* urls
* current_user
* current_account
* today

These variables are available on every page throughout the CMS. However, most of the built-in pages will have some additional variables available. To check which variables are available on the current page, there is a special tag: {% debug:help %}. It adds the list of all the top-level variables available to use as a comment in the source of the page.

The direct consequence of the context is that the liquid drops are organized in a hierarchical structure. The available set of variables only gives you the list of the top level drops that are available. Using them, you can get access to elements much deeper inside the hierarchy, as shown in the above examples.



endif::showscript[]
