:scrollbar:
:data-uri:
:noaudio:

== 3scale Developer Portal

* Hosted by 3scale 
* Provides 3scale CMS to create custom portal quickly
* A default developer portal available out of box.
* Built in pages with HTML, CSS, Javascript elements 
* Liquid tags for processing and displaying data on portal
* Authentication options:
** Username and password
** Authentication via Github
** Auth0
** Red Hat Single Sign-on integration

ifdef::showscript[]

=== Transcript


The developer portal is the site where developers can subscribe to APIs. From the developer portal, developers can manage their subscription, have access to their API key, create applications, access the interactive API documentation (ActiveDocs), see their API consumption, etc. The 3scale CMS, with its out of the box features allows to quickly create a developer portal with all what is required for on-boarding new customers. By default, 3scale generates a default developer portal with functionality for signup, dashboard, account pages, activedocs, etc. These can be customized as desired to meet the requirements of the API provider. 



endif::showscript[]
