:scrollbar:
:data-uri:


== 3scale Developer Portal

.Customizing Pages

* CMS provides version control
* Restricted pages:
** Sign-up
** Dashboard
** Account pages
* Identify elements of page using browser development tools
* Modify or hide elements:
** CSS
*** Create custom CSS
*** Link to page layout
** jQuery


ifdef::showscript[]

=== Transcript

3scale's CMS provides the ability to modify or hide elements on the system-generated pages. The CMS has a built-in version control system so that you can audit the change history and roll back to a previous version.

Note that the system-generated pages are subject to change, although this happens infrequently. These changes can break customizations that you implement. You need to monitor for disruptive changes and do the necessary maintenance to keep your portal functioning correctly.

The first and most important thing to do is to identify the elements of the page. To do that, use Firebug or other tools such as Chrome Developer tools or Opera Dragonfly. 

After identifying the elements, you can change their display settings. Depending on the type of element, you can choose from two possible methods: CSS manipulation or jQuery script. CSS manipulation is lightweight and reliable, but does not work well for some kinds of elements that exist on a number of pages. If you have a trickier element to hide, such as a sidebar menu element, use jQuery.

endif::showscript[]
