:scrollbar:
:data-uri:
:noaudio:

== 3scale Developer Portal

* Can test changes in draft mode
* Publish changes to live site
* Developer Portal can be access restriced with *access code*
* can open portal to world
* Restrict visibility as per chosen features:
** User Plans
** Multiple Services
** Multiple Applications
** Multiple Users
** Web Hooks
** Finance

ifdef::showscript[]

=== Transcript

Any changes to the developer portal can be first accessed in  a draft version to ensure the rendering is correct. Once satisfied, the draft changes can be published so that they are visible on the portal.

The developer portal can be a public site accessible to any developers with the URL, or it can be restricted and be accessible only to users with the shared access code. 

 Some advanced features of the 3scale platform are by default not visible for your developers. In other words, HTML fragments of its controls are not rendered on your developers portal so that your styling remains intact when upgrading. For example, the developers won't see a 'Create User' button on their portal if the 'Multiple Users' feature is hidden.



endif::showscript[]
