:scrollbar:
:data-uri:
:noaudio:

== Developer Sign Up Flows

* Allow sign-up of users from Developer Portal
* Signup to allow API access for account plan, service plan or application plans.
* Multiple options:
** Automated - No approvals required
** Approval - Admin to approve developer signup
** Plans - Allow plan changes directly by developers
** Default - Enable default plan for developers
* Multi-service signups

ifdef::showscript[]

=== Transcript

Signup workflows are a critical aspect of the developer experience you provide through your Developer Portal. The process can range from being completely automatic and self-service to the other extreme of requiring total control over who gains access to what, with various levels of granularity.

The 3scale platform allows you to model your API with a combination of account (optional), service (optional), and application plans. For each of these plans, you can control whether there is an approval gate that you operate. For each one, you also determine whether there is a default, or the developer is required to take the next step and make a choice.
 

For the extreme of maximum automation and self-service, remove all approval steps and enable all possible default plans. This way, a key can be issued to provide access to your API immediately after signup.

If you’re using the multiple services functionality, you’re able to customize the signup procedure to allow customers to subscribe to different services.

endif::showscript[]
