:scrollbar:
:data-uri:
:noaudio:

== Summary


* 3scale Admin and Developer Portals
* 3scale Admin Portal
* 3scale BizOps
* API Documentation
* 3scale ActiveDocs
* 3scale Developer Portal
* Liquid Programming Language
* Restricted Content
* Developer Sign-Up Flows
* 3scale Command Line Interface


ifdef::showscript[]

=== Transcript


This module introduced the features and functionality of 3scale's Administration and Developer Portals. 3scale BizOps covered managing business operation workflows, and API Documentation described creating and sharing API documentation with API consumers using 3scale ActiveDocs. The module continued with the Developer Portal and how developers subscribe to an API and use the built-in CMS to create a custom Developer Portal with everything required to on-board new customers. Next the module looked at using the Liquid programming language to add content and logic to page, manipulate email templates, and restrict page content. The module concluded with a discussion of 3scale's command line interface.




endif::showscript[]
